
version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: minipay
      POSTGRES_USER: minipay
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minipay -d minipay"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker

